spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
management:
  health:
    jms:
      enabled: ${MANAGEMENT_HEALTH_JMS_ENABLED:false}
queue:
  engineRequestQueue: whisper-engine-queue
transform:
  core:
    version: 5.4.1
  whisper:
    model: base
