spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
management:
  health:
    jms:
      enabled: ${MANAGEMENT_HEALTH_JMS_ENABLED:false}
queue:
  engineRequestQueue: xml-engine-queue
transform:
  core:
    version: 5.4.1
