# Namespace declarations
namespace.prefix.cm=http://www.alfresco.org/model/content/1.0

# Mappings from top-level XML element names to Alfresco content model properties
title=cm:title
author=cm:author
description=cm:description
subject=cm:description
keywords=cm:description
