# Namespace declarations
namespace.prefix.cm=http://www.alfresco.org/model/content/1.0

# Mappings from Excel built-in document properties (excel.* keys) to Alfresco content model
excel.title=cm:title
excel.author=cm:author
excel.subject=cm:description
excel.description=cm:description
excel.keywords=cm:description
